### ISSUE TITLE
为什么package.json不是type:module打包就报错

### ISSUE THREAD

**Issue by Miofly** [vue-macros/vue-macros#474] opened 2023-08-22 08:48 UTC
rt

**Comment by sxzz** [comment] 2023-08-23 04:25
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

https://antfu.me/posts/why-reproductions-are-required

**Closed by sxzz** 2023-08-23 04:25 UTC
