### ISSUE TITLE
`betterDefine` does not work in Rspack + Vue 2

### ISSUE THREAD

**Issue by huangtiandi1999** [vue-macros/vue-macros#812] opened 2024-09-13 10:56 UTC
### Describe the bug

my project is fork from [https://github.com/vue-macros/vue2-rspack](url), and I want to verify that betterDefine works properly in vue2 when build with Rspack

```vue
<script setup lang="ts">
import type { IProps } from './interface.ts';

defineProps<IProps>();
</script>

<template>
  <div>test: {{ msg }}</div>
</template>
```

```typescript
export interface IProps {
  msg: string;
}
```
The rspack.config.js file remains the same

`npm run build` when the build is performed, the following error occurs

![rspack](https://github.com/user-attachments/assets/3bf20df1-ba03-44c1-afd1-630229d487ac)

### Reproduction

none

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 152.05 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 4.0.2 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
    pnpm: 8.11.0 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment] 2024-09-14 03:42
Confirm that this issue can only be reproduced in Webpack/Rspack + Vue 2 (`vue-loader@15`).
We have launched a paid support plan to provide continued support for Vue 2 #373

**Comment by huangtiandi1999** [comment] 2024-09-14 08:05
> Confirm that this issue can only be reproduced in Webpack/Rspack + Vue 2 (`vue-loader@15`). We have launched a paid support plan to provide continued support for Vue 2 #373

Ok, I checked the following error in detail, @vue-macros/better-define before v1.7.1 supported Props to reference externally defined TS types, I guess this feature was broken when version 1.7.1 was released

**Comment by sxzz** [comment] 2024-12-02 02:29
Closing due to https://github.com/vue-macros/vue-macros/issues/866

**Closed by sxzz** 2024-12-02 02:29 UTC
Labels: Vue 2
