### ISSUE TITLE
jQuery type conflict

### ISSUE THREAD

**Issue by matthew-dean** [vue-macros/vue-macros#637] opened 2024-03-13 14:07 UTC
### Describe the bug

Not sure why this is only turning up now (maybe a package update?), but Vue Macros' type definition is over-writing jQuery type definitions.

Specifically, I'm now seeing TypeScript errors for lines like `$.getJSON`. When I click on the `$`, whereas I used to get `JQueryStatic`, now it links to:

```ts
declare const $: typeof import('./macros').$
```

Note: this happens even though I'm explicitly importing `$` from 'jquery'. Is there a way to remove the global `$` from vue-macros?

### Reproduction

N/A -- isn't a runtime issue

### System Info

```Shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 44.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/Library/Caches/fnm_multishells/69986_1710208129613/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/69986_1710208129613/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/69986_1710208129613/bin/npm
    pnpm: 8.10.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.128
    Safari: 17.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment] 2024-03-27 14:39
Could you please provide a reproduction?

**Comment by sxzz** [comment] 2024-06-19 14:59
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2024-06-19 14:59 UTC
