### ISSUE TITLE
Are there any plans to support rspack?

### ISSUE THREAD

**Issue by leewhite97** [vue-macros/vue-macros#653] opened 2024-03-27 09:39 UTC
### Clear and concise description of the problem

unplugin has started supporting rspack, are there plans for the same for vue-macros

### Suggested solution

powered by unplugin rspack support

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment] 2024-03-27 14:38
Most of the features of Vue Macros should now be supported by Rspack, although they haven't been introduced in the public documentation yet. You can go ahead and use it to see if there are any issues.

```ts
import VueMacros from 'unplugin-vue-macros'

VueMacros.rspack()
```

**Comment by leewhite97** [comment] 2024-03-28 01:55
> Most of the features of Vue Macros should now be supported by Rspack, although they haven't been introduced in the public documentation yet. You can go ahead and use it to see if there are any issues.
> 
> ```ts
> import VueMacros from 'unplugin-vue-macros'
> 
> VueMacros.rspack()
> ```

This doesn't work, it seems because unplugin-combine doesn't support rspack

**Comment by sxzz** [comment] 2024-03-28 07:10
Or just try `webpack` version, and see what's going on

**Comment by sxzz** [comment] 2024-03-28 09:46
Try `unplugin-vue-macros@2.8.0`

**Comment by leewhite97** [comment] 2024-03-29 07:35
Thank you so much!!

But I encountered some difficulties in getting started:
There will be a reference error such as defineOptions is not defined. 
My running environment is vue2 + rspack. 

I'm not sure if I'm missing any configuration.
here is minimal demo: https://github.com/leewhite97/vue-macros-vue2-rspack

**Comment by sxzz** [comment] 2024-03-29 15:44
I raised an issue https://github.com/web-infra-dev/rspack/issues/6068 to Rspack. Let's wait until the bug is fixed by Rspack team.

**Comment by sxzz** [comment] 2024-04-11 01:59
It should fixed in Rspack v0.6. Try template https://github.com/vue-macros/vue2-rspack

However, some features still cannot work as expected, like `defineModels`. See [unplugin docs](https://unplugin.unjs.io/guide/#supported-hooks) and issue https://github.com/web-infra-dev/rspack/issues/3408

**Comment by leewhite97** [comment] 2024-04-12 03:30
it works, awesome!!!

**Comment by sxzz** [comment] 2024-07-24 05:23
In the latest unplugin, Rspack supports all hooks. The issue is resolved.

**Closed by sxzz** 2024-07-24 05:23 UTC
Labels: enhancement, upstream
