### ISSUE TITLE
Error: The following dependencies are imported but could not be resolved:

### ISSUE THREAD

**Issue by aszx0413** [vue-macros/vue-macros#725] opened 2024-07-09 02:00 UTC
### Describe the bug

this is my code:
import { $ref } from '@vue-macros/reactivity-transform/macros';

and bug:

Error: The following dependencies are imported but could not be resolved:

  @vue-macros/reactivity-transform/macros (imported by /Users/michael/www/docms/vue-ma/src/views/archivesManage/archives/boxingModal.vue?id=0)

Are they installed?
    at file:///Users/michael/www/docms/vue-ma/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:51147:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/michael/www/docms/vue-ma/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:50652:26

### Reproduction

import { $ref } from '@vue-macros/reactivity-transform/macros';

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 172.97 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhiyuanzmj** [comment] 2024-07-21 14:32
The `$ref` is only a type, so it shouldn't be imported.

**Comment by zhiyuanzmj** [comment] 2024-07-21 14:45
Maybe we should add a `export {}`  to the end of `macros.d.ts`.

**Comment by sxzz** [comment] 2024-07-22 17:10
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed** 2024-07-24 05:22 UTC
